### ISSUE TITLE
Uninstall script does not uninstall

### ISSUE THREAD

**Issue by adekbadek** [leogermani/newspack-docker#2]
I've run `./n install`, then `./n uninstall`, then again `./n install`. I see the `WordPress has already been installed. […]` message. Looking at the `uninstall.sh` script, I see it only resets the DB and clears upload & upgrade directories, it does not uninstall the core.

**Comment by leogermani** [comment]
Ok, I figured it out.

What's happening is that memcached is caching the value for `is_blog_installed` and that's why we think WP is intalled in that script.

I'll have to make sure to flush the cache when uninstalling.

But note that uninstall is not expected to remove WP core files or wp-config, it just resets the database.
